# Generated by Django 2.2.3 on 2020-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='说明'),
        ),
    ]
